spring:
  application:
    name: payment-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  datasource:
    hikari:
      connection-timeout: 20000
      validation-timeout: 3000

server:
  port: 8080